      - name: Build Docker image (SHA + latest)
        run: |
          docker build \
            -t ghcr.io/mochthebest-byte/app:${{ github.sha }} \
            -t ghcr.io/mochthebest-byte/app:latest \
            app

      - name: Push Docker image (SHA + latest)
        run: |
          docker push ghcr.io/mochthebest-byte/app:${{ github.sha }}
          docker push ghcr.io/mochthebest-byte/app:latest
# force change понеділок, 5 січня 2026 22:22:49 +0200
